language: python

cache:
  directories:
  - "~/.platformio"

install:
- pip install -U platformio

env:
- BOARD=leonardo

before_script:
  - wget https://github.com/pololu/a-star-32u4-arduino-library/archive/1.0.5.tar.gz -O /tmp/AStar32U4.tar.gz
  - tar -xvf /tmp/AStar32U4.tar.gz
  - export PATH=$PATH:$PWD/AStar32U4

script:
- set -eo pipefail;
  for e in examples/*; do
    platformio ci --board=$BOARD --lib=. $e/*;
  done
